
Error Timestamp: 2024-01-28 15:08:08
Error Dump:
[Errno 2] No such file or directory: 'kdsjn,d'
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 18, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 10, in loader
    with open(self.file_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'kdsjn,d'

Error Timestamp: 2024-01-28 17:26:58
Error Dump:
Loader.loader() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 18, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
TypeError: Loader.loader() takes 1 positional argument but 2 were given

Error Timestamp: 2024-01-28 17:28:14
Error Dump:
Loader.loader() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 18, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
TypeError: Loader.loader() takes 1 positional argument but 2 were given

Error Timestamp: 2024-01-28 19:05:21
Error Dump:
Error: Cannot load a new program while another program is already ready to run at the same location.
Traceback (most recent call last):
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 114, in start
    self.run_command(command, args)
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 77, in run_command
    self.load_program(filename, verbose)
  File "c:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 20, in load_program
    raise ProgramLoadError()
ProgramLoadError: Error: Cannot load a new program while another program is already ready to run at the same location.

Error Timestamp: 2024-02-07 15:35:29
Error Dump:
[Errno 2] No such file or directory: 'int.osx'
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = loader.loader(verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 10, in loader
    with open(self.file_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'int.osx'

Error Timestamp: 2024-02-07 15:49:02
Error Dump:
Error: Cannot load a new program while another program is already ready to run at the same location.
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 114, in start
    self.run_command(command, args)
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 77, in run_command
    self.load_program(filename, verbose)
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 20, in load_program
    raise ProgramLoadError()
ProgramLoadError: Error: Cannot load a new program while another program is already ready to run at the same location.

Error Timestamp: 2024-02-09 10:02:55
Error Dump:
'Queue' object has no attribute 'append'
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 22, in load_program
    self.cpus.append(CPU(self.memory, self.registers, loader_address, b_size, PC, verbose))
    ^^^^^^^^^^^^^^^^
AttributeError: 'Queue' object has no attribute 'append'

Error Timestamp: 2024-02-09 10:04:26
Error Dump:
'Queue' object has no attribute 'append'
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 22, in load_program
    self.cpus.put(CPU(self.memory, self.registers, loader_address, b_size, PC, verbose))
    ^^^^^^^^^^^^^^^^
AttributeError: 'Queue' object has no attribute 'append'

Error Timestamp: 2024-02-09 10:15:35
Error Dump:
[WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 129, in start
    self.run_command(command, args)
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 103, in run_command
    self.osx(filename, verbose)
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 114, in osx
    subprocess.run(command, check=True)
  File "C:\Users\disha\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\disha\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\disha\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

Error Timestamp: 2024-02-09 10:18:53
Error Dump:
[WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 131, in start
    self.run_command(command, args)
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 103, in run_command
    self.osx(filename, verbose)
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 114, in osx
    subprocess.run(command, check=True)
  File "C:\Users\disha\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\disha\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\disha\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

Error Timestamp: 2024-02-09 10:22:51
Error Dump:
VMShell.run_program() missing 1 required positional argument: 'verbose'
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 130, in start
    args = parts[1:]
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 82, in run_command
    elif command == "run":
        ^^^^^^^^^^^^^^^^^^^
TypeError: VMShell.run_program() missing 1 required positional argument: 'verbose'

Error Timestamp: 2024-02-13 13:57:55
Error Dump:
'Loader' object has no attribute 'stack'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 136, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 109, in run_command
    self.osx(filename, verbose)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 116, in osx
    load_address = self.loader.stack[-1] + 1
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'Loader' object has no attribute 'stack'

Error Timestamp: 2024-02-13 13:59:38
Error Dump:
'Loader' object has no attribute 'stack'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 136, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 109, in run_command
    self.osx(filename, verbose)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 116, in osx
    load_address = self.loader.stack[-1] + 1
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'Loader' object has no attribute 'stack'

Error Timestamp: 2024-02-13 13:59:54
Error Dump:
[WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 136, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 109, in run_command
    self.osx(filename, verbose)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 119, in osx
    subprocess.run(command, check=True)
  File "C:\Users\brade\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\brade\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

Error Timestamp: 2024-02-13 14:01:37
Error Dump:
Command 'osx.exe int.asm 6' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 119, in osx
    subprocess.run(command, check=True, shell=True)  # Add shell=True parameter
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'osx.exe int.asm 6' returned non-zero exit status 1.

Error Timestamp: 2024-02-13 14:05:33
Error Dump:
expected str, bytes or os.PathLike object, not int
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 137, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 109, in run_command
    self.osx(filename, verbose)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 120, in osx
    subprocess.run(brkt_command, check=False, shell=True)  # Add shell=True parameter
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\brade\anaconda3\Lib\subprocess.py", line 1462, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\anaconda3\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not int

Error Timestamp: 2024-02-14 15:42:04
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 11:13:47
Error Dump:
unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 43, in run_program
    running.execute_program()  # Assuming CPU has execute_program method
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 147, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 34, in execute
    self.add(operand1, operand2, dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 67, in add
    result = value1 + value2
             ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

Error Timestamp: 2024-02-16 11:17:54
Error Dump:
unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 43, in run_program
    running.execute_program()  # Assuming CPU has execute_program method
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 147, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 34, in execute
    self.add(operand1, operand2, dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 67, in add
    result = value1 + value2
             ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

Error Timestamp: 2024-02-16 11:27:07
Error Dump:
unsupported operand type(s) for +: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 43, in run_program
    running.execute_program()  # Assuming CPU has execute_program method
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\CPU.py", line 147, in execute_program
    self.execute(instruction)
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\CPU.py", line 34, in execute
    self.add(operand1, operand2, dest_reg)
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\CPU.py", line 67, in add
    result = value1 + value2
             ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

Error Timestamp: 2024-02-16 11:34:02
Error Dump:
Memory read error: Address 10000 is out of bounds.
Traceback (most recent call last):
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\MainClass.py", line 43, in run_program
    running.execute_program()  # Assuming CPU has execute_program method
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\CPU.py", line 143, in execute_program
    instruction = self.fetch()
                  ^^^^^^^^^^^^
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\CPU.py", line 16, in fetch
    instruction.append(self.memory.read(self.loader_address+self.registers.read('PC')))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\disha\OneDrive\Documents\Design and simulation of Operating Systems\Milestone1\mainmemory.py", line 10, in read
    raise IndexError(f"Memory read error: Address {address} is out of bounds.")
IndexError: Memory read error: Address 10000 is out of bounds.

Error Timestamp: 2024-02-16 13:20:56
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 13:33:01
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 13:33:31
Error Dump:
unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 43, in run_program
    running.execute_program()  # Assuming CPU has execute_program method
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 142, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 40, in execute
    self.subtract(operand1, operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 72, in subtract
    result = value1 - value2
             ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Error Timestamp: 2024-02-16 13:33:42
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 13:34:36
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 13:46:35
Error Dump:
unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 44, in run_program
    running.execute_program()  # Assuming CPU has execute_program method
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 141, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 39, in execute
    self.subtract(operand1, operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 71, in subtract
    result = value1 - value2
             ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Error Timestamp: 2024-02-16 13:47:59
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 14:06:03
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 14:06:38
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 14:07:24
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 14:21:35
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, PC, loader_address = self.loader.loader(filename, verbose)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print_errordump('ProgramLoadError')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 14:21:50
Error Dump:
unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 47, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 146, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 41, in execute
    self.subtract(operand1, operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 73, in subtract
    result = value1 - value2
             ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Error Timestamp: 2024-02-16 14:29:45
Error Dump:
unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 47, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 146, in execute_program
    print('todo')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 41, in execute
    elif opcode == 17:  # opcode for SUBTRACT
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 73, in subtract
    value2 = self.registers.read(f'R{operand2}')
             ^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Error Timestamp: 2024-02-16 14:30:28
Error Dump:
'VMShell' object has no attribute 're'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 26, in load_program
    print(self.re)
          ^^^^^^^
AttributeError: 'VMShell' object has no attribute 're'

Error Timestamp: 2024-02-16 14:30:32
Error Dump:
'VMShell' object has no attribute 're'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 26, in load_program
    print(self.re)
          ^^^^^^^
AttributeError: 'VMShell' object has no attribute 're'

Error Timestamp: 2024-02-16 14:36:22
Error Dump:
unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 147, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 42, in execute
    self.subtract(operand1, operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 74, in subtract
    result = value1 - value2
             ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Error Timestamp: 2024-02-16 14:37:09
Error Dump:
list index out of range
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 152, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 118, in run_command
    if args[1]:
       ~~~~^^^
IndexError: list index out of range

Error Timestamp: 2024-02-16 14:37:38
Error Dump:
list index out of range
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 152, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 118, in run_command
    if args[1]:
       ~~~~^^^
IndexError: list index out of range

Error Timestamp: 2024-02-16 14:38:20
Error Dump:
list index out of range
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 152, in start
    self.run_command(command, args)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 118, in run_command
    if args[1]:
       ~~~~^^^
IndexError: list index out of range

Error Timestamp: 2024-02-16 14:39:51
Error Dump:
unsupported operand type(s) for -: 'str' and 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 147, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 42, in execute
    self.subtract(operand1, operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 74, in subtract
    result = value1 - value2
             ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'str'

Error Timestamp: 2024-02-16 14:57:11
Error Dump:
Memory read error: Address 10000 is out of bounds.
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 145, in execute_program
    instruction = self.fetch()
                  ^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 18, in fetch
    instruction.append(self.memory.read(self.loader_address+self.current_instruction_address))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\mainmemory.py", line 10, in read
    raise IndexError(f"Memory read error: Address {address} is out of bounds.")
IndexError: Memory read error: Address 10000 is out of bounds.

Error Timestamp: 2024-02-16 14:58:09
Error Dump:
can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 149, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 46, in execute
    self.multiply(operand1,operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 87, in multiply
    result = value1 * value2
             ~~~~~~~^~~~~~~~
TypeError: can't multiply sequence by non-int of type 'str'

Error Timestamp: 2024-02-16 15:02:10
Error Dump:
not writable
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, first_instruction_address, loader_address = self.loader.loader(filename, verbose)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 17, in loader
    self.print('loader class err')
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 228, in print_errordump
    file.write(error)
io.UnsupportedOperation: not writable

Error Timestamp: 2024-02-16 15:03:16
Error Dump:
can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 149, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 46, in execute
    self.multiply(operand1,operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 87, in multiply
    result = value1 * value2
             ~~~~~~~^~~~~~~~
TypeError: can't multiply sequence by non-int of type 'str'

Error Timestamp: 2024-02-16 15:06:02
Error Dump:
Memory write error: Address 1331113482 is out of bounds.
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 23, in load_program
    b_size, first_instruction_address, loader_address = self.loader.loader(filename, verbose)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\loader.py", line 31, in loader
    self.memory.write(loader_address,directives_code)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\mainmemory.py", line 16, in write
    raise IndexError(f"Memory write error: Address {address} is out of bounds.")
IndexError: Memory write error: Address 1331113482 is out of bounds.

Error Timestamp: 2024-02-16 15:06:08
Error Dump:
can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 149, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 46, in execute
    self.multiply(operand1,operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 87, in multiply
    result = value1 * value2
             ~~~~~~~^~~~~~~~
TypeError: can't multiply sequence by non-int of type 'str'

Error Timestamp: 2024-02-16 15:06:57
Error Dump:
can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 149, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 46, in execute
    self.multiply(operand1,operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 87, in multiply
    result = value1 * value2
             ~~~~~~~^~~~~~~~
TypeError: can't multiply sequence by non-int of type 'str'

Error Timestamp: 2024-02-21 10:49:12
Error Dump:
can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 150, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 45, in execute
    self.multiply(operand1,operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 88, in multiply
    result = value1 * value2
TypeError: can't multiply sequence by non-int of type 'str'

Error Timestamp: 2024-02-22 15:04:01
Error Dump:
can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 150, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 45, in execute
    self.multiply(operand1,operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 88, in multiply
    result = value1 * value2
TypeError: can't multiply sequence by non-int of type 'str'

Error Timestamp: 2024-02-22 15:06:39
Error Dump:
can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 48, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 150, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 45, in execute
    self.multiply(operand1,operand2,dest_reg)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 88, in multiply
    result = value1 * value2
TypeError: can't multiply sequence by non-int of type 'str'

Error Timestamp: 2024-02-22 15:26:27
Error Dump:
invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\MainClass.py", line 49, in run_program
    running.execute_program()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 150, in execute_program
    self.execute(instruction)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\CPU.py", line 57, in execute
    swi1.executeSWI(destination)
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\SWI.py", line 14, in executeSWI
    self.input_stuff()
  File "C:\Users\brade\Documents\A School Work\OS\Group OS\Design-and-simulation-of-Operating-Systems\Design-and-simulation-of-Operating-Systems\Milestone1\SWI.py", line 24, in input_stuff
    self.registers.write('R2', int(value1))
ValueError: invalid literal for int() with base 10: ''
